title: "Christian's Homelab Dashboard"
documentTitle: "Christian's Homelab Dashboard"
logo: "https://homer-prod-1.kube-prod-1.home.clcreative.de/assets/gaming_avatar.jpg"

theme: default
header: true
footer: false

defaults:
  layout: list
  colorTheme: auto

stylesheet:
  - "assets/custom.css"

columns: "3"
connectivityCheck: false
colors:
  light:
    highlight-primary: "transparent"
    highlight-secondary: "transparent"
    highlight-hover: "transparent"
    background: "#f5f5f5d0"
    card-background: "#ffffffc5"
    text: "#fafafa"
    text-header: "#fafafa"
    text-title: "#363636"
    text-subtitle: "#363636"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#0167ff"
    link-hover: "#0167ff"
    background-image: "https://homer-prod-1.kube-prod-1.home.clcreative.de/assets/background.png"
  dark:
    highlight-primary: "transparent"
    highlight-secondary: "transparent"
    highlight-hover: "transparent"
    background: "#131313d0"
    card-background: "#2b2b2bc5"
    text: "#fafafa"
    text-header: "#fafafa"
    text-title: "#fafafa"
    text-subtitle: "#fafafa"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#0167ff"
    link-hover: "#0167ff"
    background-image: "https://homer-prod-1.kube-prod-1.home.clcreative.de/assets/background.png"

# message:
#   style: "is-info"
#   title: "Welcome to"
#   icon: "fa fa-info"
#   content: "CL Creative Infrastructure Dashboard"

# links:
#   - name: "GitHub: ChristianLempa"
#     icon: "fab fa-github"
#     url: "https://github.com/christianlempa"
#     target: "_blank"
#   - name: "GitHub: CLCreative"
#     icon: "fab fa-github"
#     url: "https://github.com/clcreative"
#     target: "_blank"

services:

  - name: "Infra"
    icon: "fas fa-power-off"
    items:
      - name: "Sophos XG Firewall"
        icon: "fas fa-shield"
        subtitle: "Network Firewall"
        url: "https://fw-prod-1.home.clcreative.de"
        target: "_blank"
      - name: "Sophos Switch"
        icon: "fas fa-network-wired"
        subtitle: "Network Switch"
        url: "https://sw-prod-1.home.clcreative.de"
        target: "_blank"
      - name: "Proxmox"
        icon: "fas fa-server"
        subtitle: "Virtualization"
        url: "https://prx-prod-2.home.clcreative.de:8006/"
        target: "_blank"
      - name: "TrueNAS Scale"
        icon: "fas fa-hdd"
        subtitle: "Network Attached Storage"
        url: "https://nas-prod-1.home.clcreative.de"
        target: "_blank"

  - name: "Apps"
    icon: "fab fa-app-store-ios"
    items:
      - name: "Homer Dashboard"
        icon: "fas fa-tachometer-alt"
        subtitle: "Homelab Dashboard"
        url: "https://homer-prod-1.kube-prod-1.home.clcreative.de"
        target: "_blank"
      - name: "Ansible Semaphore"
        icon: "fa-solid fa-wand-magic-sparkles"
        subtitle: "Ansible UI"
        url: "https://ansiblesemaphore-prod-1.srv-prod-1.home.clcreative.de"
        target: "_blank"
      - name: "UptimeKuma"
        icon: "fa-solid fa-list-check"
        subtitle: "Uptime Monitoring"
        url: "https://uptimekuma-prod-1.kube-prod-1.home.clcreative.de"
        target: "_blank"
      - name: "Portainer"
        icon: "fab fa-docker"
        subtitle: "Docker and Kubernetes Management"
        url: "https://portainer-prod-1.kube-prod-1.home.clcreative.de"
        target: "_blank"
      - name: "ArgoCD"
        icon: "fa-solid fa-infinity"
        subtitle: "Continuous Delivery for Kubernetes"
        url: "https://argocd-prod-1.kube-prod-1.home.clcreative.de"
        target: "_blank"
      - name: "Grafana"
        icon: "fa-solid fa-chart-column"
        subtitle: "Metrics and Dashboards"
        url: "https://grafana-prod-1.srv-prod-1.home.clcreative.de/"
        target: "_blank"

  - name: "Cloud"
    icon: "fas fa-cloud"
    items:
      - name: "Teleport"
        icon: "fas fa-fingerprint"
        subtitle: "Secure Authentication"
        url: "https://clcreative.teleport.sh/"
        target: "_blank"
      - name: "Datree"
        icon: "fa-solid fa-wind"
        subtitle: "Kubernetes Policies and Security"
        url: "https://app.datree.io/"
        target: "_blank"
      - name: "Armo"
        icon: "fa-solid fa-virus-covid"
        subtitle: "Kubernetes Compliance and Security"
        url: "https://cloud.armosec.io/"
        target: "_blank"