name: Update Inventory File

on:
  push:
    branches:
      - main
    paths:
      - 'ansible/inventory/*'

jobs:
  deploy:
    runs-on: "self-hosted"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: SCP files via ssh key
        uses: appleboy/scp-action@master
        with:
          username: xcad
          host: srv-prod-1.home.clcreative.de
          key: ${{ secrets.SSH_XCAD }}
          source: './ansible/inventory/*'
          target: '/home/xcad/ansiblesemaphore-prod-1/'
