name: Update Config Files

on:
  push:
    branches:
      - main
      - test
      - dev
    paths:
      - 'dns/dns-prod-1/config/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: "self-hosted"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: SCP files via ssh key
        uses: appleboy/scp-action@master
        with:
          username: xcad
          host: srv-prod-7.home.clcreative.de
          key: ${{ secrets.SSH_XCAD }}
          source: './config/*'
          target: '/home/xcad/dns-prod-1/'
          overwrite: true

      - name: Restart Docker Container
        uses: fifsky/ssh-action@master
        with:
          user: xcad
          host: srv-prod-7.home.clcreative.de
          key: ${{ secrets.SSH_XCAD }}
          command: |
            cd dns-prod-1
            docker compose restart
